#!/bin/bash

# 编译函数
compile() {
    # 获取不带扩展名的文件名
    local base_name=$(basename "$1" .cpp)

    clang++ -DSTATIC_CONCPP -I /usr/include/mysql-cppconn-8 \
    -o "$base_name" "$1" /usr/lib64/libmysqlcppconnx-static.a -lssl -lcrypto -lresolv

    if [ $? -eq 0 ]; then
        echo "编译成功，生成可执行文件: $base_name"
    else
        echo "编译失败"
    fi
}

# 检查参数数量
if [ $# -eq 0 ]; then
    echo "请输入 cpp 文件名作为参数"
else 
    # 调用编译函数，传入第一个参数
    compile "$1"
fi
