#traverse_dfs: AMGraph.c traverse_dfs.c 
#	gcc -o traverse_dfs AMGraph.c traverse_dfs.c
traverse_bfs: AMGraph.c traverse_bfs.c 
	gcc -o traverse_bfs AMGraph.c traverse_bfs.c
#Prim: AMGraph.c Prim.c 
#	gcc -o Prim Prim.c AMGraph.c
